"""Generator für moduleigene ``START.bat``/``start.sh`` aus ``roles[]``."""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
import stat
import subprocess
from typing import Callable, Sequence

from .adapters import AdapterError
from .session import build_session_plan

GENERATED_MARKER = "Generated by COMA roles[] starter generator."


@dataclass(frozen=True)
class RoleDeclaration:
    module_id: str
    role_id: str
    label: str
    prompt_file: Path
    request: str
    providers: tuple[str, ...]

    @property
    def key(self) -> str:
        return f"{self.module_id}:{self.role_id}"


def load_roles(manifest_file: str | os.PathLike[str]) -> tuple[RoleDeclaration, ...]:
    path = Path(manifest_file).expanduser().resolve()
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise AdapterError(f"Rollenmanifest nicht lesbar: {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise AdapterError("Rollenmanifest muss ein JSON-Objekt sein")
    module_id = str(payload.get("id") or "").strip()
    roles = payload.get("roles")
    if not module_id or not isinstance(roles, list):
        raise AdapterError("Rollenmanifest braucht id und roles[]")
    result: list[RoleDeclaration] = []
    for raw in roles:
        if not isinstance(raw, dict):
            continue
        role_id = str(raw.get("id") or "").strip().lower()
        prompt = str(raw.get("prompt") or "").strip()
        request = str(raw.get("request") or "").strip()
        providers = tuple(
            str(value).strip().lower()
            for value in raw.get("providers", [])
            if str(value).strip()
        )
        if not role_id or not prompt or not request or not providers:
            continue
        prompt_file = (path.parent / prompt).resolve()
        if not prompt_file.is_file():
            raise AdapterError(f"Prompt-Datei nicht gefunden: {prompt_file}")
        result.append(RoleDeclaration(
            module_id=module_id,
            role_id=role_id,
            label=str(raw.get("label") or role_id).strip(),
            prompt_file=prompt_file,
            request=request,
            providers=providers,
        ))
    if not result:
        raise AdapterError("Kein vollständiger roles[]-Eintrag gefunden")
    return tuple(result)


def _replace_allowed(path: Path, force: bool) -> bool:
    if not path.exists() or force:
        return True
    try:
        return GENERATED_MARKER in path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return False


def generate_starters(
    manifest_file: str | os.PathLike[str],
    output_dir: str | os.PathLike[str],
    *,
    force: bool = False,
) -> tuple[Path, Path]:
    """Schreibt zwei dünne, wiederholbar generierbare Forwarder."""
    manifest = Path(manifest_file).expanduser().resolve()
    load_roles(manifest)  # vollständiger Vertrag vor dem ersten Write
    target = Path(output_dir).expanduser().resolve()
    target.mkdir(parents=True, exist_ok=True)
    windows = target / "START.bat"
    posix = target / "start.sh"
    for path in (windows, posix):
        if not _replace_allowed(path, force):
            raise AdapterError(
                f"Vorhandener handgeschriebener Starter bleibt unangetastet: {path}"
            )

    relative = os.path.relpath(manifest, target)
    windows_manifest = relative.replace("/", "\\")
    posix_manifest = relative.replace("\\", "/")
    windows.write_text(
        "@echo off\n"
        f"rem {GENERATED_MARKER}\n"
        "@chcp 65001 >nul\n"
        "setlocal\n"
        f"set \"ROLE_MANIFEST=%~dp0{windows_manifest}\"\n"
        "python -c \"import unified_gui.console\" >nul 2>&1\n"
        "if errorlevel 1 goto coma_fallback\n"
        "python -m unified_gui.console start --manifest \"%ROLE_MANIFEST%\" %*\n"
        "exit /b %ERRORLEVEL%\n"
        ":coma_fallback\n"
        "echo [FALLBACK] unified-gui-Konsole fehlt; verwende COMA.\n"
        "python -m coma starters run --manifest \"%ROLE_MANIFEST%\" %*\n"
        "exit /b %ERRORLEVEL%\n",
        encoding="utf-8",
        newline="\n",
    )
    posix.write_text(
        "#!/usr/bin/env sh\n"
        f"# {GENERATED_MARKER}\n"
        "set -eu\n"
        "starter_dir=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n"
        f"role_manifest=\"$starter_dir/{posix_manifest}\"\n"
        "if python -c 'import unified_gui.console' >/dev/null 2>&1; then\n"
        "  exec python -m unified_gui.console start --manifest \"$role_manifest\" \"$@\"\n"
        "fi\n"
        "echo '[FALLBACK] unified-gui-Konsole fehlt; verwende COMA.'\n"
        "exec python -m coma starters run --manifest \"$role_manifest\" \"$@\"\n",
        encoding="utf-8",
        newline="\n",
    )
    posix.chmod(posix.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return windows, posix


def select_role(roles: Sequence[RoleDeclaration], value: str) -> RoleDeclaration:
    wanted = str(value).strip().lower()
    if wanted.isdigit() and 1 <= int(wanted) <= len(roles):
        return roles[int(wanted) - 1]
    matches = [
        role for role in roles
        if wanted in {role.role_id.lower(), role.label.lower(), role.key.lower()}
    ]
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        raise AdapterError(f"Rolle {value!r} ist mehrdeutig; modul:rolle verwenden")
    raise AdapterError(f"Unbekannte Rolle {value!r}")


def run_starter(
    manifest_file: str | os.PathLike[str],
    *,
    role: str = "",
    provider: str = "",
    model: str = "",
    effort: str = "",
    cwd: str | os.PathLike[str] | None = None,
    dry_run: bool = False,
    input_fn: Callable[[str], str] = input,
    run=subprocess.run,
) -> int:
    roles = load_roles(manifest_file)
    if not role:
        print("Verfügbare Modulrollen:")
        for index, item in enumerate(roles, 1):
            print(f"  [{index}] {item.key} — {item.label}")
        role = input_fn("Rolle (Nummer oder Name): ")
    selected = select_role(roles, role)
    provider = provider.strip().lower()
    if not provider:
        print("Anbieter:")
        for index, name in enumerate(selected.providers, 1):
            print(f"  [{index}] {name}")
        answer = input_fn(f"Anbieter [Enter = {selected.providers[0]}]: ").strip()
        if answer.isdigit() and 1 <= int(answer) <= len(selected.providers):
            provider = selected.providers[int(answer) - 1]
        else:
            provider = answer.lower() or selected.providers[0]
    if provider not in selected.providers:
        raise AdapterError(
            f"Provider {provider!r} ist für {selected.key} nicht erlaubt"
        )
    plan = build_session_plan(
        provider,
        prompt_file=selected.prompt_file,
        request=selected.request,
        mode="interactive",
        model=model,
        effort=effort,
        session_name=selected.key.replace(":", "-"),
        cwd=cwd,
    )
    print(f"[START] {selected.key} über COMA/{provider}")
    for command in plan.commands:
        print(subprocess.list2cmdline(list(command)))
    if dry_run:
        return 0
    for command in plan.commands:
        completed = run(list(command), cwd=plan.cwd, check=False)
        if completed.returncode:
            return int(completed.returncode)
    return 0


__all__ = [
    "GENERATED_MARKER", "RoleDeclaration", "generate_starters", "load_roles",
    "run_starter", "select_role",
]
